var app = angular.module('portfolio', ['ngAnimate','ui.bootstrap']);

app.controller('mainController', function($scope, $rootScope, $window, $location, $http, scrollToElement) {

  $scope.showModal = false;
  $scope.selectedPhoto = "df951b3939cc50e91c9148730fc7b1df";
  $scope.contactInfo = false;

  //flickr related data
  var apiKey = ""
  var photosetIds = [];

  //contact Information
  $scope.emailText = "";
  $scope.addressText = "";
  $scope.phoneText = "";

  //social media information
  $scope.githubUrl="https://github.com/dhruvsinghal";
  $scope.linkedInUrl="https://www.linkedin.com/in/singhaldhruv"

  // json object containing professional experience data
  $scope.experience = [{
    imageUrl:"css/images/cornellLogo.png",
    company:"Cornell University",
    title:"Graduate Teaching Assistant",
    location:"Ithaca, NY",
    duration:"Aug 2015 - Present",
    description : [
    "Fall 2015: Systems Programming and Computer Architecture (CS 3410)",
    "Spring 2016: Computer Vision (CS 4670) [Head Teaching Assistant]",
    "Fall 2016, Spring 2017: Operating Systems (CS 4410) and Operating Systems Practicum"
    ]
  },
  {
    imageUrl:"css/images/facebookLogo.png",
    company:"Facebook",
    title:"Software Engineering Intern",
    location:"Menlo Park, CA" ,
    duration:"Jun 2016 - Aug 2016",
    description : [
    "Added full Unicode support to Facebook's Watchman service (github.com/facebook/watchman) in C and Python.",
    "Created a Python AsyncIO client for interacting with the Watchman service using Python 3.5 and above."
    ]
  },
  {
    imageUrl:"css/images/googleLogo.jpg",
    company:"Google",
    title:"Software Engineering Intern",
    location:"San Bruno, CA",
    duration:"June 2015 - Aug 2015",
    description : [
    "Made improvements to the backend used by YouTube Mix to recommend related music videos as "
    +"well as for broad music search queries by integrating high quality signals generated by two different "
    +"internal groups. The work was done exclusively in C++."
    ]
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    company:"Cornell University",
    title:"Undergraduate Teaching Assistant",
    location:"Ithaca, NY",
    duration: "Jan 2015 - May 2015",
    description: [
    "Introduction to Computer Vision (CS 4670).",
    "Proposed and implemented the conversion of projects on Feature Detection and Panorama Stitching from the"+
    " past course offering from C++ to Python.",
    "Contributed to the implementation and testing of a project on Convolutional Neural Networks.",
    "Graded quizzes, exams, assignments, and projects and held weekly office hours."
    ]
  },
  {
    imageUrl:"css/images/googleLogo.jpg",
    company:"Google",
    title:"Engineering Practicum Intern",
    location:"New York City",
    duration: "May 2014 - Aug 2014",
    description: [
    "Made schema changes to an internal No-SQL database of employees and products.",
    "Modified existing Google Cloud Endpoints API to accommodate the schema changes.",
    "Created an interactive home page for the web application that provides a view into the database using AngularJS."
    ]
  }];

  //JSON object containing education related data
  $scope.education = [
  {
    imageUrl:"css/images/cornellLogo.png",
    university:"Cornell University",
    course:"Master of Science(B.S.) in Engineering, Computer Science",
    duration:"2015 - 2017"
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    university:"Cornell University",
    course:"Bachelor of Science(B.S.) in Engineering, Computer Science",
    duration:"2012 - 2015"
  }
  ];

  //JSON object containing personal projects related data
  $scope.projects =[
  {
    imageUrl:"css/images/cornellLogo.png",
    title : 'cuautograde',
    description : 'Tools for processing student assignments submitted via CMS.',
    githubUrl : 'https://github.com/cuautograde/cuautograde',
    technologies : 'Python'
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    title : 'Aegis Password Manager',
    description : 'The password manager for teams!',
    githubUrl : 'https://github.com/dhruvsinghal/aegis-password-manager',
    technologies : 'Java'
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    title : 'Build P4FPGA from Source',
    description : 'Build P4FPGA from Source',
    githubUrl : 'https://github.com/dhruvsinghal/p4fpga',
    technologies : 'C++'
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    title : 'Watchman',
    description : 'Watchman exists to watch files and record when they actually change. It can also trigger actions (such as rebuilding assets) when matching files change.',
    githubUrl : '',
    technologies : 'C'
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    title : 'Frenetic',
    description : 'Frenetic is an open-source Software Defined Network (SDN) controller platform designed to make SDN programming easy, modular, and semantically correct.',
    githubUrl : 'https://github.com/dhruvsinghal/watchman',
    technologies : 'OCaml'
  },
  {
    imageUrl:"css/images/cornellLogo.png",
    title : 'Command line tools',
    description : 'This is a successor to my previous terminal configuration system term-tools.',
    githubUrl : 'https://github.com/dhruvsinghal/term-tools-neo',
    technologies : 'Shell'
  }
  ];

  $scope.photographs = [
  {
    category : 'Category 1',
    photos : ['css/images/photo1.jpg','css/images/photo2.jpg','css/images/photo3.jpg','css/images/photo4.jpg','css/images/photo5.jpg']
  },
  {
    category : 'Category 2',
    photos : ['css/images/photo6.jpg','css/images/photo7.jpg','css/images/photo8.jpg','css/images/photo9.jpg','css/images/photo10.jpg']
  },
  {
    category : 'Category 3',
    photos : ['css/images/photo11.jpg','css/images/photo12.jpg','css/images/photo13.jpg','css/images/photo14.jpg']
  }
  ];

  $scope.redirectToGithub = function(index){
    $window.location.href=$scope.projects[index].githubUrl;
  }

  $scope.redirectPage = function(url){
    $window.location.href=url;
  }

  $scope.toggleModal = function(photo){
    $scope.selectedPhoto = photo;
    $scope.showModal = !$scope.showModal;
  }

  $scope.showContactInfo = function(){
    
    $scope.emailText = atob('ZGhydXZAc2luZ2hhbC5tZQ==');
    $scope.addressText = atob('MTUxIERyeWRlbiBSb2FkLCBBcHQgNTIwLCBJdGhhY2Es' +
    'IE5ZIDE0ODUw');
    $scope.phoneText = atob('KzEgKDYwNykgMjc5LTU3Mjk=');
    $scope.contactInfo = !$scope.contactInfo;
  }

  $scope.gotoElement = function (id){
      scrollToElement.scrollTo(id);
      
    };

});

app.directive('experienceBox',['$window',function($window){ 
  return{
    restrict:'A',
    replace:true,
    scope:{
      info : '='
    },
    templateUrl:'templates/professionalExperienceTemplate.html',
    link:function(scope,element,attrs){

      scope.showDescription = { secondFace : true };
      scope.expandBox = function(){
        scope.showDescription.secondFace = !scope.showDescription.secondFace;
      }
    
    }
 };
}]);

app.directive('modalWindow',function(){
  return{
    restrict:'E',
    scope:{
    showVariable : '='
    },
    replace: true,
    transclude:true,
    templateUrl:'templates/modalTemplate.html',
    link:function(scope,element,attrs){
      scope.sizeStyle = {};
      if (attrs.width)
        scope.sizeStyle.width = attrs.width;
      if (attrs.height)
        scope.sizeStyle['min-width'] = attrs.height;
      scope.hideModal = function(){
        scope.showVariable=false;
      }
    }
  };
});

app.service('scrollToElement', function(){
this.scrollTo = function(id) {
        
        var startYPosition = currentYPosition();
        var stopYPosition = elementYPosition(id);
        var distance = stopYPosition > startYPosition ? stopYPosition - startYPosition : startYPosition - stopYPosition;
        if (distance < 100) {
            scrollTo(0, stopYPosition); return;
        }
        var speed = Math.round(distance / 100);
        if (speed >= 20) speed = 20;
        var step = Math.round(distance / 25);
        var leapY = stopYPosition > startYPosition ? startYPosition + step : startYPosition - step;
        var timer = 0;
        if (stopYPosition > startYPosition) {
            for ( var i=startYPosition; i<stopYPosition; i+=step ) {
                setTimeout("window.scrollTo(0, "+leapY+")", timer * speed);
                leapY += step; if (leapY > stopYPosition) leapY = stopYPosition; timer++;
            } return;
        }
        for ( var i=startYPosition; i>stopYPosition; i-=step ) {
            setTimeout("window.scrollTo(0, "+leapY+")", timer * speed);
            leapY -= step; if (leapY < stopYPosition) leapY = stopYPosition; timer++;
        }
        
        function currentYPosition() {
            if (self.pageYOffset) return self.pageYOffset;
            return 0;
        }
        
        function elementYPosition(id) {
            var element = document.getElementById(id);
            var y = element.offsetTop;
            var node = element;
            while (node.offsetParent && node.offsetParent != document.body) {
                node = node.offsetParent;
                y += node.offsetTop;
            } return y;
        }

    };
    
});
